// Schemas
export { Profile, ProfileSchema } from './profile.schema.js'
export type { ProfileDocument } from './profile.schema.js'
export { Skill, SkillSchema } from './skill.schema.js'
export type { SkillDocument } from './skill.schema.js'
export { Issue, IssueSchema } from './issue.schema.js'
export type { IssueDocument } from './issue.schema.js'
export { PullRequest, PullRequestSchema } from './pull-request.schema.js'
export type { PullRequestDocument } from './pull-request.schema.js'
export { Comment, CommentSchema } from './comment.schema.js'
export type { CommentDocument } from './comment.schema.js'
export { Preference, PreferenceSchema } from './preference.schema.js'
export type { PreferenceDocument } from './preference.schema.js'
export { Discussion, DiscussionSchema } from './discussion.schema.js'
export type { DiscussionDocument } from './discussion.schema.js'
export { ProfileJob, ProfileJobSchema, PROFILE_JOB_STEP_NAMES } from './profile-job.schema.js'
export type { ProfileJobDocument, ProfileJobStepName, ProfileJobStepStatus, ProfileJobStatus } from './profile-job.schema.js'

// Repository abstracts + Mongo implementations
export { ProfileRepository, ProfileRepositoryMongo } from './profile.repository.js'
export { SkillRepository, SkillRepositoryMongo } from './skill.repository.js'
export { IssueRepository, IssueRepositoryMongo } from './issue.repository.js'
export { PullRequestRepository, PullRequestRepositoryMongo } from './pull-request.repository.js'
export { CommentRepository, CommentRepositoryMongo } from './comment.repository.js'
export { PreferenceRepository, PreferenceRepositoryMongo } from './preference.repository.js'
export { DiscussionRepository, DiscussionRepositoryMongo } from './discussion.repository.js'
export { ProfileJobRepository, ProfileJobRepositoryMongo } from './profile-job.repository.js'

// In-memory implementations (for tests)
export { ProfileRepositoryInMemory } from './profile.repository.inmemory.js'
export { SkillRepositoryInMemory } from './skill.repository.inmemory.js'
export { IssueRepositoryInMemory } from './issue.repository.inmemory.js'
export { PullRequestRepositoryInMemory } from './pull-request.repository.inmemory.js'
export { CommentRepositoryInMemory } from './comment.repository.inmemory.js'
export { PreferenceRepositoryInMemory } from './preference.repository.inmemory.js'
export { DiscussionRepositoryInMemory } from './discussion.repository.inmemory.js'
export { ProfileJobRepositoryInMemory } from './profile-job.repository.inmemory.js'
